import type React from "react"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { GeistMono } from "geist/font/mono"
import { Analytics } from "@vercel/analytics/next"
import { Suspense } from "react"
import { dark } from "@clerk/themes"
import {
    ClerkProvider,
    SignedIn,
    SignedOut,
    UserButton,
} from "@clerk/nextjs"
import "./globals.css"

export const dynamic = "force-dynamic"

export const metadata: Metadata = {
    title: "Clerk Next.js Quickstart",
    description: "Generated by create next app",
}

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-inter",
})

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode
}>) {
    // Make sure the publishable key exists
    const clerkKey = process.env.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
    if (!clerkKey) {
        throw new Error(
            "Clerk publishable key missing. Add NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY to your .env"
        )
    }

    return (
        <ClerkProvider publishableKey={clerkKey} // Ensure NEXT_PUBLIC_ key is used
                       appearance={{ baseTheme: dark }}>
            <html lang="en" className="dark">
            <body className={`font-sans ${inter.variable} ${GeistMono.variable}`}>
            {/* Header */}
            <header className="p-4 flex items-center justify-end gap-2 border-b border-primary/50">
                <SignedOut>
                    {/* You can remove SignInButton/SignUpButton if you use a login page */}
                    <div className="flex gap-2">
                        <button className="btn btn-primary">
                            <a href="/login" className="btn btn-outline">
                                Login
                            </a>
                        </button>
                    </div>
                </SignedOut>
                <SignedIn>
                    <UserButton />
                </SignedIn>
            </header>

            {/* Page content */}
            <Suspense fallback={null}>{children}</Suspense>

            {/* Analytics */}
            <Analytics />
            </body>
            </html>
        </ClerkProvider>
    )
}
